# Generated by Django 6.0.4 on 2026-04-08 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('provider', models.CharField(choices=[('canvas', 'Canvas'), ('blackboard', 'Blackboard')], max_length=32)),
                ('mode', models.CharField(choices=[('demo', 'Demo'), ('live', 'Live')], default='demo', max_length=16)),
                ('auth_type', models.CharField(choices=[('oauth', 'OAuth'), ('token', 'Token')], default='token', max_length=16)),
                ('base_url', models.URLField(blank=True)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('credential_hint', models.CharField(blank=True, max_length=255)),
                ('status_message', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('provider', 'display_name'),
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], default='started', max_length=16)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('items_imported', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.lmsconnection')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
    ]
