# Generated by Django 6.0.4 on 2026-04-08 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lmsconnection',
            index=models.Index(fields=['user', 'provider'], name='lms_user_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='lmsconnection',
            index=models.Index(fields=['user', 'is_active'], name='lms_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['connection', '-started_at'], name='synclog_connection_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='lmsconnection',
            constraint=models.UniqueConstraint(fields=('user', 'display_name'), name='uniq_lms_connection_name_per_user'),
        ),
    ]
