# Generated by Django 6.0.4 on 2026-04-08 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('instructor', models.CharField(blank=True, max_length=255)),
                ('color_hex', models.CharField(default='#1f6feb', max_length=7)),
                ('current_grade_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='integrations.lmsconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
                'unique_together': {('user', 'connection', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='GradeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(max_length=120)),
                ('weight_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('override_weight_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source', models.CharField(choices=[('lms', 'LMS'), ('manual', 'Manual')], default='lms', max_length=16)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_components', to='academics.course')),
            ],
            options={
                'ordering': ('course', 'name'),
                'unique_together': {('course', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('assignment', 'Assignment'), ('exam', 'Exam'), ('quiz', 'Quiz'), ('project', 'Project'), ('manual', 'Manual Task')], default='assignment', max_length=32)),
                ('due_at', models.DateTimeField()),
                ('weight_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=16)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_points', models.DecimalField(decimal_places=2, default=100, max_digits=7)),
                ('earned_score_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('imported', 'Imported'), ('manual', 'Manual')], default='imported', max_length=16)),
                ('priority_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='integrations.lmsconnection')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='academics.course')),
                ('grade_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='academics.gradecomponent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_at', '-priority_score'),
            },
        ),
    ]
