# Generated by Django 6.0.4 on 2026-04-08 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('integrations', '0002_lmsconnection_lms_user_provider_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='gradecomponent',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['user', 'title'], name='course_user_title_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'is_completed', 'due_at'], name='task_user_due_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['course', 'due_at'], name='task_course_due_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'priority_score'], name='task_user_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('connection__isnull', False), models.Q(('external_id', ''), _negated=True)), fields=('user', 'connection', 'external_id'), name='uniq_imported_course_external_id'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('current_grade_percent__gte', 0), ('current_grade_percent__lte', 100)), name='course_current_grade_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='gradecomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('course', 'external_id'), name='uniq_grade_component_external_id'),
        ),
        migrations.AddConstraint(
            model_name='gradecomponent',
            constraint=models.CheckConstraint(condition=models.Q(('weight_percent__gte', 0), ('weight_percent__lte', 100)), name='grade_component_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='gradecomponent',
            constraint=models.CheckConstraint(condition=models.Q(('override_weight_percent__isnull', True), models.Q(('override_weight_percent__gte', 0), ('override_weight_percent__lte', 100)), _connector='OR'), name='grade_component_override_weight_range'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'imported'), ('connection__isnull', False), models.Q(('external_id', ''), _negated=True)), fields=('user', 'connection', 'external_id'), name='uniq_imported_task_external_id'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('weight_percent__gte', 0), ('weight_percent__lte', 100)), name='task_weight_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_hours__gte', 0)), name='task_estimated_hours_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('max_points__gt', 0)), name='task_max_points_positive'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('earned_score_percent__isnull', True), models.Q(('earned_score_percent__gte', 0), ('earned_score_percent__lte', 100)), _connector='OR'), name='task_earned_score_percent_range'),
        ),
    ]
