# Generated by Django 6.0.4 on 2026-04-08 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_course_unique_together_and_more'),
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studyavailability',
            index=models.Index(fields=['user', 'weekday'], name='availability_user_weekday_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'start_at'], name='session_user_start_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'status', 'start_at'], name='session_user_status_start_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyavailability',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='study_availability_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='studyavailability',
            constraint=models.UniqueConstraint(fields=('user', 'weekday', 'start_time', 'end_time'), name='uniq_user_availability_slot'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='study_session_end_after_start'),
        ),
    ]
